version: '1.0'
services:
  api:
    build: .
    ports:
      - "8080:8080"
  postgres_dev:
    container_name: 'postgres-dev'
    image: 'postgres:14.1-alpine'
    env_file:
      - .env
    ports:
      - '54320:5432'
    volumes:
      - postgres_data:/data/postgres
    restart: unless-stopped
volumes:
  postgres_data:
